<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'image' => ['required', 'mimes: jpg,jpg', 'dimensions: min_width=300, min_height=300'],
        ];
    }

//    public function attributes()
//    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
//    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
//        return [
//            'image.required' => 'Изображение обязательно должно быть заполнено',
//        ];
    }
}
